### ISSUE TITLE
Fix Windows Installer (Exotic - Gui issue)

### ISSUE THREAD

**Issue by Kevin14m** [rzellem/EXOTIC#966] opened 2022-03-06 21:31 UTC
During the running of the software, i meet a problem where the cmd says that "Exotic - Gui" is not known

**Comment by Kevin14m** [comment] 2022-03-07 17:13
Yes, of course

**Comment by rzellem** [comment] 2022-03-07 17:16
ah! So this is a known issue and @jpl-jengelke is actively making the fix. The problem is that the install/run script is not properly linking things on a Windows machine (well, it used to, but then something on the Windows side changes). John is hoping to have a fix released by this week.

In the meantime, you can manually launch the GUI by opening up a command line / terminal and then changing directories to your main EXOTIC folder and then typing:
`python3 exotic/exotic_gui.py`
or
`python3 exotic_gui.py`
(depending on what directory you're in)

**Comment by jpl-jengelke** [comment] 2022-03-09 14:27
See issue #735

**Comment by jpl-jengelke** [comment] 2022-03-09 18:39
Please try a workaround of [installing Git Bash at this link](https://gitforwindows.org/). There is further detail (though it is perhaps over-detailed for what is necessary now at [this link](https://github.com/rzellem/EXOTIC/issues/27#issuecomment-644391430).) The change from the detailed instructions to today is that MS Visual Studio may only need to be installed with the C++ options.

**Comment by jpl-jengelke** [comment] 2022-03-09 18:40
Closing as a DUPLICATE of ticket #735

**Closed** 2022-05-04 16:35 UTC
Labels: bug
